name: Github Pages
on: 
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: actions/setup-node@v2
      uses: actions/setup-node@v4   
      with:
        node-version: '20.4'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: install yarn 
      uses: npm install yarn
    - run: yarn install && yarn build  
    - name: upload files 
      uses: actions/upload-artifact@v4
      with: 
        name: build-pages
        retention-days: 1
  Deploy: 
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: download build files
        uses: actions/download-artifact@v4
        with:
          name: build-pages
          path: dist
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: dist
          token: "${{ secrets.DEPLOY_TOKEN }}"  